language: c
sudo: false
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - nasm
      - diffutils
compiler:
  - clang
  - gcc
matrix:
    exclude:
        - os: osx
          compiler: gcc
cache:
  directories:
    - libav-samples
before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install nasm; fi
script:
  - mkdir -p libav-samples
  - ./configure --samples=libav-samples --cc=$CC
  - make -j 8
  - make fate-rsync
  - make check -j 8
